import type { DetailTemplate } from './types'

export const BEAUTY_TEMPLATES: DetailTemplate[] = [
  {
    id: 'beauty_skincare_01',
    name: '스킨케어/기초화장품',
    description: '피부 개선 효능과 성분 신뢰도를 과학적으로 전달',
    category: 'beauty',
    visualTone: 'minimal',
    colorFamily: 'clean-white',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'NanumSquareNeo',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Pretendard Variable',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '스킨케어 — 신뢰감 있는 라운드 산세리프 + 클린 세리프 스토리 + 모노스페이스 계열 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'ingredients', 'process', 'certifications', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'icon-feature-row',
      ingredients: 'grid-info-cards',
      process: 'numbered-steps-horizontal',
      certifications: 'centered-statement',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '화이트/크림/라이트 피치 팔레트. 클린뷰티 느낌의 투명하고 맑은 톤. 모던 산세리프 타이포. 피부 텍스처 클로즈업 사진. 성분 인포그래픽 스타일. 인증 마크 눈에 띄게.',
  },
  {
    id: 'beauty_luxury_02',
    name: '럭셔리/프리미엄 뷰티',
    description: '고급 화장품의 격조 있는 아름다움과 효능을 표현',
    category: 'beauty',
    visualTone: 'premium',
    colorFamily: 'dark-luxury',
    fontMood: 'elegant',
    fontPairing: {
      headlineFont: 'Hahmlet',
      storyFont:    'Gowun Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'Song Myung',
      rationale:    '럭셔리 뷰티 — 에디토리얼 세리프 헤드라인 + 우아한 세리프 스토리 + 전통 명조 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'sensory', 'key_benefit', 'ingredients', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      sensory: 'full-bleed-overlay',
      key_benefit: 'grid-info-cards',
      ingredients: 'split-text-heavy',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '딥 블랙/미드나잇 네이비/골드 팔레트. 박스 패키지의 고급스러운 질감 강조. 세리프 헤드라인. 럭셔리 호텔 욕실 같은 스타일링. 금빛 광택 디테일.',
  },
  {
    id: 'beauty_natural_03',
    name: '자연/비건 뷰티',
    description: '천연 원료와 친환경 가치를 따뜻하게 전달',
    category: 'beauty',
    visualTone: 'natural',
    colorFamily: 'warm-cream',
    fontMood: 'natural',
    fontPairing: {
      headlineFont: 'GmarketSans',
      storyFont:    'Gowun Batang',
      bodyFont:     'Noto Sans KR',
      accentFont:   'Nanum Pen Script',
      rationale:    '자연/비건 뷰티 — 친근한 산세리프 헤드라인 + 따뜻한 세리프 스토리 + 손글씨 감성 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'ingredients', 'process', 'key_benefit', 'certifications', 'photo_gallery', 'cta'],
    patternOverrides: {
      brand_story: 'split-text-heavy',
      ingredients: 'timeline-vertical',
      process: 'numbered-steps-horizontal',
      key_benefit: 'icon-feature-row',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '아이보리/세이지 그린/베이지 팔레트. 보태니컬 식물 원료 사진. 린넨·황마 텍스처 배경. 손글씨 느낌 세리프. 비건·유기농 인증 강조. 자연광 촬영.',
  },
  {
    id: 'beauty_color_04',
    name: '색조화장품',
    description: '트렌디한 색감과 발색력을 생생하게 표현',
    category: 'beauty',
    visualTone: 'bold',
    colorFamily: 'vibrant',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Paperlogy',
      storyFont:    'Noto Sans KR',
      bodyFont:     'Gothic A1',
      accentFont:   'Stylish',
      rationale:    '색조화장품 — 볼드 임팩트 헤드라인 + 깔끔한 본문 + 세련된 액센트',
    },
    sectionSequence: ['hero', 'sensory', 'key_benefit', 'photo_gallery', 'ingredients', 'social_proof', 'packaging', 'cta'],
    patternOverrides: {
      sensory: 'full-bleed-overlay',
      key_benefit: 'icon-feature-row',
      photo_gallery: 'masonry-gallery',
      social_proof: 'testimonial-quote',
      ingredients: 'grid-info-cards',
    },
    artDirectorHints: '비비드 컬러 팔레트 (제품 색조 반영). 다양한 피부톤 모델 착용 사진. 볼드한 타이포. 발색 클로즈업 필수. 트렌디한 패션 매거진 레이아웃.',
  },
  {
    id: 'beauty_antiaging_05',
    name: '안티에이징/기능성',
    description: '임상 효능과 과학적 근거로 신뢰를 구축',
    category: 'beauty',
    visualTone: 'minimal',
    colorFamily: 'clean-white',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'NanumSquareNeo',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Pretendard Variable',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '안티에이징 — 신뢰감 있는 라운드 산세리프 + 과학적 세리프 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'process', 'ingredients', 'comparison', 'certifications', 'photo_gallery', 'cta'],
    patternOverrides: {
      key_benefit: 'grid-info-cards',
      process: 'timeline-vertical',
      ingredients: 'icon-feature-row',
      comparison: 'comparison-table',
      certifications: 'centered-statement',
    },
    artDirectorHints: '화이트/실버/라이트 그레이 팔레트. 의료·과학적인 클린 디자인. 수치 데이터·임상 결과 인포그래픽. 비포&애프터 비교. 더마 브랜드 느낌.',
  },
  {
    id: 'beauty_korean_06',
    name: 'K-뷰티/트렌드',
    description: 'K-뷰티 특유의 귀엽고 트렌디한 감성으로 글로벌 공략',
    category: 'beauty',
    visualTone: 'bold',
    colorFamily: 'soft-pink',
    fontMood: 'casual',
    fontPairing: {
      headlineFont: 'Sunflower',
      storyFont:    'Gowun Dodum',
      bodyFont:     'Gothic A1',
      accentFont:   'Hi Melody',
      rationale:    'K-뷰티 — 경쾌한 산세리프 헤드라인 + 귀여운 둥근 스토리 + 비정형 손글씨 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'sensory', 'photo_gallery', 'ingredients', 'social_proof', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'grid-info-cards',
      sensory: 'full-bleed-overlay',
      photo_gallery: 'masonry-gallery',
      social_proof: 'testimonial-quote',
      ingredients: 'split-text-heavy',
    },
    artDirectorHints: '파스텔 핑크/라벤더/민트 팔레트. K-뷰티 특유의 귀여운 일러스트 활용. 패키지 클로즈업 + 모델 착용 사진. 소셜 후기·별점 강조. 밝고 생기있는 분위기.',
  },
  {
    id: 'beauty_haircare_07',
    name: '헤어케어',
    description: '건강하고 빛나는 모발을 위한 솔루션 표현',
    category: 'beauty',
    visualTone: 'natural',
    colorFamily: 'warm-cream',
    fontMood: 'elegant',
    fontPairing: {
      headlineFont: 'GmarketSans',
      storyFont:    'Nanum Myeongjo',
      bodyFont:     'Noto Sans KR',
      accentFont:   'Gowun Batang',
      rationale:    '헤어케어 — 친근한 산세리프 헤드라인 + 부드러운 명조 스토리 + 따뜻한 세리프 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'ingredients', 'process', 'how_to_use', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'icon-feature-row',
      ingredients: 'grid-info-cards',
      process: 'timeline-vertical',
      how_to_use: 'numbered-steps-horizontal',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '앰버/골드/크림 팔레트. 촉촉하고 윤기 있는 모발 클로즈업. 원재료(아르간오일, 케라틴 등) 이미지. 사용 단계 사진. 따뜻하고 부드러운 라이팅.',
  },
  {
    id: 'beauty_mens_08',
    name: '남성 그루밍',
    description: '남성 라이프스타일에 맞는 세련되고 간결한 표현',
    category: 'beauty',
    visualTone: 'premium',
    colorFamily: 'dark-luxury',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Paperlogy',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Pretendard Variable',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '남성 그루밍 — 볼드 임팩트 헤드라인 + 세련된 세리프 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'key_benefit', 'how_to_use', 'ingredients', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      key_benefit: 'grid-info-cards',
      how_to_use: 'numbered-steps-horizontal',
      ingredients: 'icon-feature-row',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '챠콜/딥 그레이/오프화이트 팔레트. 남성적이고 미니멀한 레이아웃. 모던 산세리프 타이포. 면도/세안 라이프스타일 사진. 간결하고 실용적인 카피.',
  },
  {
    id: 'beauty_bodycare_09',
    name: '바디케어/향수',
    description: '관능적인 향과 피부 감촉을 감각적으로 전달',
    category: 'beauty',
    visualTone: 'warm',
    colorFamily: 'earth',
    fontMood: 'elegant',
    fontPairing: {
      headlineFont: 'Hahmlet',
      storyFont:    'Gowun Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'Nanum Brush Script',
      rationale:    '바디케어/향수 — 감성적 세리프 헤드라인 + 따뜻한 세리프 스토리 + 붓글씨 관능 액센트',
    },
    sectionSequence: ['hero', 'sensory', 'brand_story', 'ingredients', 'key_benefit', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      sensory: 'full-bleed-overlay',
      brand_story: 'split-text-heavy',
      ingredients: 'centered-statement',
      key_benefit: 'icon-feature-row',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '테라코타/모카/샌드 팔레트. 피부 위 제품 클로즈업. 향의 원료 소재 배치 (꽃잎, 허브, 나무). 관능적이고 따뜻한 라이팅. 에디토리얼 스타일링.',
  },
  {
    id: 'beauty_story_10',
    name: '뷰티 브랜드 스토리',
    description: '창업자의 비전과 브랜드 철학으로 감성적 유대 형성',
    category: 'beauty',
    visualTone: 'editorial',
    colorFamily: 'warm-cream',
    fontMood: 'serif-heavy',
    fontPairing: {
      headlineFont: 'KoPub Batang',
      storyFont:    'Hahmlet',
      bodyFont:     'Noto Sans KR',
      accentFont:   'Nanum Pen Script',
      rationale:    '뷰티 스토리 — 에디토리얼 명조 헤드라인 + 감성 세리프 스토리 + 손글씨 감성 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'philosophy', 'process', 'ingredients', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      philosophy: 'centered-statement',
      process: 'timeline-vertical',
      ingredients: 'split-text-heavy',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '에디토리얼 매거진 스타일. 크림/아이보리/소프트 로즈 팔레트. 창업자/연구실 사진 중심. 세리프+산세리프 혼합 타이포. 긴 카피와 여백 활용. 뷰티 철학 스토리텔링.',
  },
]
