import type { DetailTemplate } from './types'

export const ELECTRONICS_TEMPLATES: DetailTemplate[] = [
  {
    id: 'electronics_flagship_01',
    name: '플래그십/프리미엄 가전',
    description: '최첨단 기술력과 혁신 스펙을 직관적으로 전달',
    category: 'electronics',
    visualTone: 'premium',
    colorFamily: 'dark-luxury',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Paperlogy',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Pretendard Variable',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '플래그십 가전 — 볼드 임팩트 헤드라인 + 프리미엄 세리프 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'key_benefit', 'process', 'comparison', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      key_benefit: 'grid-info-cards',
      process: 'numbered-steps-horizontal',
      comparison: 'comparison-table',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '미드나잇 블랙/딥 그레이/실버 팔레트. 제품 누끼컷 + 다크 배경. 기술 사양 인포그래픽. 볼드 산세리프 타이포. 하이테크 제품 스튜디오 촬영 느낌. 수치 데이터 강조.',
  },
  {
    id: 'electronics_lifestyle_02',
    name: '라이프스타일 전자제품',
    description: '일상과 자연스럽게 어우러지는 감성적인 사용 경험 표현',
    category: 'electronics',
    visualTone: 'minimal',
    colorFamily: 'clean-white',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'NanumSquareNeo',
      storyFont:    'Gowun Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'Stylish',
      rationale:    '라이프스타일 전자 — 부드러운 라운드 헤드라인 + 감성 세리프 스토리 + 클린 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'key_benefit', 'how_to_use', 'photo_gallery', 'comparison', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'split-text-heavy',
      key_benefit: 'icon-feature-row',
      how_to_use: 'timeline-vertical',
      photo_gallery: 'masonry-gallery',
      comparison: 'comparison-table',
    },
    artDirectorHints: '화이트/라이트 그레이/소프트 베이지 팔레트. 생활공간에 놓인 제품 라이프스타일 사진. 미니멀 산세리프. 실제 사용 시나리오 강조. 애플 스타일 클린 레이아웃.',
  },
  {
    id: 'electronics_audio_03',
    name: '오디오/사운드 기기',
    description: '청각적 경험과 프리미엄 음질을 시각적으로 표현',
    category: 'electronics',
    visualTone: 'premium',
    colorFamily: 'midnight-blue',
    fontMood: 'elegant',
    fontPairing: {
      headlineFont: 'Hahmlet',
      storyFont:    'KoPub Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '오디오 — 감성적 세리프 헤드라인 + 고급 명조 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'key_benefit', 'sensory', 'how_to_use', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      key_benefit: 'grid-info-cards',
      sensory: 'full-bleed-overlay',
      how_to_use: 'icon-feature-row',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '딥 네이비/차콜/골드 팔레트. 음악·소리를 시각화한 웨이브폼 그래픽. 이어폰·헤드폰 클로즈업. 스튜디오·라이브 공간 라이프스타일. 음악적이고 감성적인 카피.',
  },
  {
    id: 'electronics_health_04',
    name: '헬스케어/웨어러블',
    description: '건강 관리 기능과 데이터 중심 가치를 신뢰감 있게 전달',
    category: 'electronics',
    visualTone: 'minimal',
    colorFamily: 'clean-white',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'GmarketSans',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Gothic A1',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '헬스케어 — 신뢰감 있는 산세리프 헤드라인 + 과학적 세리프 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'process', 'how_to_use', 'comparison', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'icon-feature-row',
      process: 'timeline-vertical',
      how_to_use: 'numbered-steps-horizontal',
      comparison: 'comparison-table',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '화이트/라이트 블루/그린 팔레트. 착용 라이프스타일 사진. 헬스 데이터 시각화(심박수, 수면 그래프). 의료적 신뢰감. 실제 측정치 강조. 스마트워치/밴드 클로즈업.',
  },
  {
    id: 'electronics_smarthome_05',
    name: '스마트홈/IoT',
    description: '연결된 삶의 편의성과 스마트함을 직관적으로 설명',
    category: 'electronics',
    visualTone: 'minimal',
    colorFamily: 'midnight-blue',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Tenada',
      storyFont:    'Noto Sans KR',
      bodyFont:     'Pretendard Variable',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '스마트홈 — 개성 있는 미래형 헤드라인 + 클린 산세리프 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'how_to_use', 'process', 'comparison', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'grid-info-cards',
      how_to_use: 'numbered-steps-horizontal',
      process: 'icon-feature-row',
      comparison: 'comparison-table',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '화이트/라이트 그레이/테크 블루 팔레트. 스마트홈 인테리어 라이프스타일. 앱 연동 UI 스크린샷. 설치/설정 단계 사진. 아이콘 기반 호환성 안내. 편의성 시나리오 중심.',
  },
  {
    id: 'electronics_gaming_06',
    name: '게이밍 기기',
    description: '고성능 게이밍 경험과 몰입감을 강렬하게 표현',
    category: 'electronics',
    visualTone: 'bold',
    colorFamily: 'dark-luxury',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Paperlogy',
      storyFont:    'Noto Sans KR',
      bodyFont:     'Gothic A1',
      accentFont:   'Tenada',
      rationale:    '게이밍 — 강렬한 임팩트 헤드라인 + 클린 산세리프 스토리 + 개성 있는 미래형 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'sensory', 'how_to_use', 'comparison', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'grid-info-cards',
      sensory: 'full-bleed-overlay',
      how_to_use: 'icon-feature-row',
      comparison: 'comparison-table',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '블랙/딥 퍼플/네온 엑센트 팔레트. 게이밍 셋업 사진. RGB 조명 효과. 볼드하고 강렬한 타이포. 프레임레이트·반응속도 수치 강조. 게이밍 라이프스타일 연출.',
  },
  {
    id: 'electronics_kitchen_07',
    name: '주방/생활가전',
    description: '요리와 생활의 편리함을 따뜻하고 실용적으로 표현',
    category: 'electronics',
    visualTone: 'warm',
    colorFamily: 'warm-cream',
    fontMood: 'casual',
    fontPairing: {
      headlineFont: 'GmarketSans',
      storyFont:    'Gowun Batang',
      bodyFont:     'Noto Sans KR',
      accentFont:   'Jua',
      rationale:    '주방가전 — 친근한 산세리프 헤드라인 + 따뜻한 세리프 스토리 + 활기찬 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'key_benefit', 'how_to_use', 'ingredients', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'split-text-heavy',
      key_benefit: 'icon-feature-row',
      how_to_use: 'numbered-steps-horizontal',
      ingredients: 'grid-info-cards',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '크림/웜 화이트/따뜻한 우드 팔레트. 주방 라이프스타일 사진. 요리 결과물 클로즈업. 사용 편의성 단계 안내. 인테리어와 어우러지는 제품 스타일링.',
  },
  {
    id: 'electronics_computer_08',
    name: '컴퓨터/노트북',
    description: '생산성과 성능 스펙을 전문가 관점에서 명확히 전달',
    category: 'electronics',
    visualTone: 'minimal',
    colorFamily: 'clean-white',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'NanumSquareNeo',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Pretendard Variable',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '컴퓨터/노트북 — 신뢰감 있는 산세리프 헤드라인 + 전문적 세리프 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'comparison', 'process', 'how_to_use', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'grid-info-cards',
      comparison: 'comparison-table',
      process: 'icon-feature-row',
      how_to_use: 'timeline-vertical',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '실버/화이트/스페이스 그레이 팔레트. 제품 디테일 클로즈업(포트, 키보드, 디스플레이). 사용 시나리오 사진(카페, 오피스). 스펙 비교표 중심. 프로페셔널 생산성 강조.',
  },
  {
    id: 'electronics_camera_09',
    name: '카메라/촬영 장비',
    description: '촬영 경험과 결과물의 품질을 크리에이티브하게 전달',
    category: 'electronics',
    visualTone: 'editorial',
    colorFamily: 'earth',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Hahmlet',
      storyFont:    'Gowun Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'GmarketSans',
      rationale:    '카메라 — 감성적 세리프 헤드라인 + 따뜻한 세리프 스토리 + 세련된 산세리프 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'sensory', 'process', 'how_to_use', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'icon-feature-row',
      sensory: 'full-bleed-overlay',
      process: 'grid-info-cards',
      how_to_use: 'numbered-steps-horizontal',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '블랙/다크 그레이/앰버 팔레트. 카메라로 찍은 사진 갤러리 중심. 렌즈·셔터 클로즈업. 촬영 현장 라이프스타일. 사진작가·유튜버 타겟. 샘플 촬영 결과물 강조.',
  },
  {
    id: 'electronics_eco_10',
    name: '친환경/에너지 절약 가전',
    description: '환경 가치와 에너지 효율을 신뢰감 있게 전달',
    category: 'electronics',
    visualTone: 'natural',
    colorFamily: 'fresh-green',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'GmarketSans',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Noto Sans KR',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '친환경 가전 — 신뢰감 있는 산세리프 헤드라인 + 과학적 세리프 스토리 + 테크 계열 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'brand_story', 'process', 'comparison', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'icon-feature-row',
      brand_story: 'split-text-heavy',
      process: 'timeline-vertical',
      comparison: 'comparison-table',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '에메랄드/프레시 그린/화이트 팔레트. 자연·지속가능성 이미지. 에너지 절약 수치 인포그래픽. 친환경 인증 강조. 깨끗하고 신선한 분위기.',
  },
]
