import type { DetailTemplate } from './types'

export const FOOD_TEMPLATES: DetailTemplate[] = [
  {
    id: 'food_natural_01',
    name: '자연주의/유기농',
    description: '자연 원료와 건강을 강조하는 따뜻한 크림 톤',
    category: 'food',
    visualTone: 'natural',
    colorFamily: 'warm-cream',
    fontMood: 'natural',
    fontPairing: {
      headlineFont: 'GmarketSans',
      storyFont:    'Gowun Batang',
      bodyFont:     'Noto Sans KR',
      accentFont:   'Nanum Pen Script',
      rationale:    '자연주의 — 친근한 산세리프 헤드라인 + 따뜻한 세리프 스토리 + 손글씨 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'key_benefit', 'ingredients', 'process', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'split-text-heavy',
      key_benefit: 'icon-feature-row',
      ingredients: 'grid-info-cards',
      process: 'timeline-vertical',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '크림/베이지/아이보리 팔레트. 자연 소재 텍스처 배경. 손글씨 느낌의 세리프 헤드라인. 제품 주변에 허브·곡물·원재료 배치. 전체적으로 따뜻하고 믿음직한 분위기.',
  },
  {
    id: 'food_premium_02',
    name: '프리미엄 구르메',
    description: '다크 럭셔리 배경으로 고급 식품 가치를 극대화',
    category: 'food',
    visualTone: 'premium',
    colorFamily: 'dark-luxury',
    fontMood: 'elegant',
    fontPairing: {
      headlineFont: 'Paperlogy',
      storyFont:    'KoPub Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'GmarketSans',
      rationale:    '프리미엄 구르메 — 임팩트 헤드라인 + 고급 명조 스토리 + 세련된 산세리프 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'sensory', 'key_benefit', 'process', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      sensory: 'full-bleed-sensory',
      key_benefit: 'grid-info-cards',
      process: 'numbered-steps-horizontal',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '딥 초콜릿/미드나잇 블랙 배경. 금빛 액센트 (#C8A96E 계열). 세리프 헤드라인 + 고급스러운 레이아웃. 어두운 테이블 위 제품 사진. 레스토랑 수준의 플레이팅 느낌.',
  },
  {
    id: 'food_handmade_03',
    name: '수제/홈메이드',
    description: '장인 정신과 손수 만드는 따뜻함을 표현',
    category: 'food',
    visualTone: 'warm',
    colorFamily: 'earth',
    fontMood: 'casual',
    fontPairing: {
      headlineFont: 'Tenada',
      storyFont:    'Nanum Myeongjo',
      bodyFont:     'Gothic A1',
      accentFont:   'Nanum Brush Script',
      rationale:    '수제 감성 — 개성 있는 헤드라인 + 따뜻한 명조 스토리 + 붓글씨 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'process', 'ingredients', 'photo_gallery', 'key_benefit', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'split-text-heavy',
      process: 'timeline-vertical',
      ingredients: 'left-image-right-text',
      photo_gallery: 'photo-gallery-strip',
      key_benefit: 'grid-info-cards',
    },
    artDirectorHints: '오트밀/테라코타/따뜻한 브라운 팔레트. 나무 도마·린넨 식보 등 소품 배치. 손으로 쓴 듯한 서체. 제조 과정 사진 강조. 가정집 주방 느낌의 따뜻한 라이팅.',
  },
  {
    id: 'food_health_04',
    name: '건강기능식품',
    description: '과학적 신뢰성과 건강 효능을 명확하게 전달',
    category: 'food',
    visualTone: 'minimal',
    colorFamily: 'clean-white',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'NanumSquareNeo',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Noto Sans KR',
      accentFont:   'IBM Plex Sans KR',
      rationale:    '건강기능식품 — 신뢰감 있는 산세리프 헤드라인 + 과학적 클린 본문 + 모노스페이스 계열 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'ingredients', 'certifications', 'process', 'comparison', 'packaging', 'cta'],
    patternOverrides: {
      key_benefit: 'icon-feature-row',
      ingredients: 'grid-info-cards',
      certifications: 'centered-statement',
      process: 'numbered-steps-horizontal',
      comparison: 'comparison-table',
    },
    artDirectorHints: '화이트/라이트 그레이/민트 그린 팔레트. 클린하고 의료적인 느낌. 산세리프 타이포. 성분 인포그래픽 스타일. 인증 마크 강조. 수치/데이터 중심 카피.',
  },
  {
    id: 'food_traditional_05',
    name: '전통/한식',
    description: '한국 전통 식품의 깊은 맛과 역사를 표현',
    category: 'food',
    visualTone: 'warm',
    colorFamily: 'earth',
    fontMood: 'serif-heavy',
    fontPairing: {
      headlineFont: 'KoPub Batang',
      storyFont:    'Hahmlet',
      bodyFont:     'KoPub Dotum',
      accentFont:   'Yeon Sung',
      rationale:    '전통/한식 — 격조 있는 명조 헤드라인 + 세리프 스토리 + 전통 디스플레이 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'history', 'process', 'ingredients', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      history: 'timeline-vertical',
      process: 'numbered-steps-horizontal',
      ingredients: 'grid-info-cards',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '황토/단청 붉은색/한지 베이지 팔레트. 한국 전통 문양을 배경 패턴으로 활용. 붓글씨 느낌의 세리프 헤드라인. 옹기·질그릇·소반 등 전통 소품. 역사와 장인 정신 강조.',
  },
  {
    id: 'food_minimal_06',
    name: '미니멀 브랜드',
    description: '군더더기 없는 미니멀 디자인으로 제품 본연에 집중',
    category: 'food',
    visualTone: 'minimal',
    colorFamily: 'clean-white',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Sunflower',
      storyFont:    'Gowun Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'Stylish',
      rationale:    '미니멀 — 기하학적 산세리프 헤드라인 + 여백감 있는 세리프 스토리 + 클린 액센트',
    },
    sectionSequence: ['hero', 'philosophy', 'key_benefit', 'photo_gallery', 'ingredients', 'social_proof', 'packaging', 'cta'],
    patternOverrides: {
      philosophy: 'centered-statement',
      key_benefit: 'grid-info-cards',
      photo_gallery: 'masonry-gallery',
      ingredients: 'icon-feature-row',
      social_proof: 'testimonial-quote',
    },
    artDirectorHints: '순백/오프화이트/라이트 그레이 팔레트. 여백을 적극 활용. 모던 산세리프 타이포. 제품만 단독으로 촬영한 클린컷 이미지. 불필요한 장식 요소 최소화.',
  },
  {
    id: 'food_fresh_07',
    name: '신선식품',
    description: '싱싱함과 자연의 생동감을 생생하게 전달',
    category: 'food',
    visualTone: 'natural',
    colorFamily: 'fresh-green',
    fontMood: 'casual',
    fontPairing: {
      headlineFont: 'GmarketSans',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Gothic A1',
      accentFont:   'Jua',
      rationale:    '신선식품 — 생동감 있는 산세리프 헤드라인 + 신뢰감 세리프 스토리 + 활기찬 액센트',
    },
    sectionSequence: ['hero', 'key_benefit', 'process', 'ingredients', 'photo_gallery', 'packaging', 'delivery_info', 'cta'],
    patternOverrides: {
      key_benefit: 'icon-feature-row',
      process: 'timeline-vertical',
      ingredients: 'left-image-right-text',
      photo_gallery: 'masonry-gallery',
      delivery_info: 'grid-info-cards',
    },
    artDirectorHints: '연초록/에메랄드/흰색 팔레트. 수확 직후 느낌의 싱싱한 채소·과일 이미지. 자연광 라이팅. 산지 직송 강조. 당일/새벽 배송 정보 눈에 띄게. 생동감 있는 색감.',
  },
  {
    id: 'food_gift_08',
    name: '선물세트/명절',
    description: '프리미엄 포장과 선물의 가치를 강조',
    category: 'food',
    visualTone: 'premium',
    colorFamily: 'warm-cream',
    fontMood: 'elegant',
    fontPairing: {
      headlineFont: 'KoPub Batang',
      storyFont:    'Nanum Myeongjo',
      bodyFont:     'KoPub Dotum',
      accentFont:   'GmarketSans',
      rationale:    '선물세트 — 격조 있는 명조 헤드라인 + 품격 있는 세리프 스토리 + 세련된 산세리프 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'key_benefit', 'packaging', 'comparison', 'photo_gallery', 'delivery_info', 'cta'],
    patternOverrides: {
      brand_story: 'split-text-heavy',
      key_benefit: 'grid-info-cards',
      packaging: 'right-image-left-text',
      comparison: 'comparison-table',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '골드/버건디/아이보리 팔레트. 고급 박스·리본·포장지 강조. 선물 받는 순간의 감동 연출. 구성품 상세 안내. 명절 무드.',
  },
  {
    id: 'food_trendy_09',
    name: '트렌디/인스타감성',
    description: 'MZ세대를 겨냥한 트렌디하고 바이럴한 감성',
    category: 'food',
    visualTone: 'bold',
    colorFamily: 'vibrant',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Paperlogy',
      storyFont:    'Noto Sans KR',
      bodyFont:     'Gothic A1',
      accentFont:   'Gamja Flower',
      rationale:    '트렌디/인스타 — 볼드 임팩트 헤드라인 + 깔끔한 본문 + 귀여운 손글씨 액센트',
    },
    sectionSequence: ['hero', 'sensory', 'key_benefit', 'photo_gallery', 'social_proof', 'ingredients', 'packaging', 'cta'],
    patternOverrides: {
      sensory: 'full-bleed-overlay',
      key_benefit: 'icon-feature-row',
      photo_gallery: 'masonry-gallery',
      social_proof: 'testimonial-quote',
      ingredients: 'grid-info-cards',
    },
    artDirectorHints: '비비드 컬러 또는 트렌디한 그라디언트. 볼드한 타이포그래피. 인스타그램 감성 사진. 후기/리뷰 강조. 유행어/해시태그 활용. 도전적이고 활기찬 톤.',
  },
  {
    id: 'food_story_10',
    name: '브랜드 스토리 중심',
    description: '창업자의 철학과 브랜드 히스토리로 감성 유대감 형성',
    category: 'food',
    visualTone: 'editorial',
    colorFamily: 'earth',
    fontMood: 'serif-heavy',
    fontPairing: {
      headlineFont: 'Hahmlet',
      storyFont:    'KoPub Batang',
      bodyFont:     'Pretendard Variable',
      accentFont:   'Nanum Pen Script',
      rationale:    '브랜드 스토리 — 에디토리얼 세리프 헤드라인 + 고급 명조 스토리 + 손글씨 감성 액센트',
    },
    sectionSequence: ['hero', 'brand_story', 'history', 'philosophy', 'process', 'photo_gallery', 'packaging', 'cta'],
    patternOverrides: {
      brand_story: 'dark-story-centered',
      history: 'timeline-vertical',
      philosophy: 'centered-statement',
      process: 'split-text-heavy',
      photo_gallery: 'masonry-gallery',
    },
    artDirectorHints: '에디토리얼 매거진 스타일. 브라운/모카/크림 팔레트. 창업자/제조 현장 사진 중심. 세리프 + 산세리프 혼합 타이포. 긴 카피와 여백 활용. 감성 스토리텔링 우선.',
  },
  // ── 레퍼런스 추출 템플릿 (자동 채점 100점, 디자이너 검수 전) ──
  {
    id: 'food_matcha_ref01',
    name: '자연주의 말차 프리미엄형',
    description: '제주 녹차/말차 시즌 한정 제품을 위한 청량한 그린 팔레트 기반 프리미엄 식품 상세페이지 템플릿',
    category: 'food',
    visualTone: 'natural',
    colorFamily: 'fresh-green',
    fontMood: 'modern',
    fontPairing: {
      headlineFont: 'Montserrat',
      storyFont:    'Noto Serif KR',
      bodyFont:     'Noto Sans KR',
      accentFont:   'DM Serif Display',
      rationale:    'Montserrat의 강한 디스플레이와 Noto 계열 한국어 폰트로 프리미엄·신뢰감을 동시에 확보',
    },
    sectionSequence: [
      'hero',
      'brand_story',
      'features',
      'comparison',
      'certifications',
      'benefits',
      'how_to_use',
      'ingredients',
      'social_proof',
      'packaging',
      'story',
      'cta',
    ],
    patternOverrides: {
      hero:           'full-bleed-hero',
      brand_story:    'full-bleed-sensory',
      features:       'icon-feature-row',
      comparison:     'comparison-table',
      certifications: 'grid-info-cards',
      benefits:       'numbered-steps-horizontal',
      how_to_use:     'numbered-steps-horizontal',
      ingredients:    'split-text-heavy',
      social_proof:   'testimonial-quote',
      packaging:      'photo-gallery-strip',
      story:          'full-bleed-overlay',
      cta:            'centered-statement',
    },
    artDirectorHints: '히어로 섹션은 #3A7D44 그린 그라디언트 위에 화이트 볼드 타이포를 얹어 여름 한정 느낌을 극대화할 것. 인증(HACCP·EWG·비건) 섹션은 짙은 포레스트 그린 배경에 화이트 카드 그리드로 신뢰감을 형성하고, 번호 배지(01·02·03)로 계층을 명확히 표현한다. 리뷰 섹션은 세이지 그린 헤더 배너와 소프트 섀도우 화이트 카드 조합을 유지하며 별점을 골드(#C8A84B)로 강조한다. 전체 페이지는 밝은 그린 → 짙은 그린의 색온도 내러티브로 \'여름 청량감\'에서 \'프리미엄 품질\'로 자연스럽게 전환되도록 섹션 배경색을 교차 배치한다.',
    colorTokens: {
      primary:    '#3A7D44',
      secondary:  '#6AAB5E',
      background: '#F5F7F2',
      text:       '#1E2E1A',
      accent:     '#C8A84B',
    },
    validatedAt: '',  // 디자이너 검수 전 (자동 채점 100점)
  },
]
